version: "3.8"

services:
  api:
   build: ./api
   container_name: e-norm-api
   ports:
    - 3000:3000
   networks:
    - web
    - database
   restart: unless-stopped

  app:
   build: ./app
   container_name: e-norm-web-app
   volumes:
    - ./app:/usr/share/nginx/html
   ports:
    - 8080:80
   networks:
    - web
   restart: unless-stopped

  db:
    image: postgres:latest
    container_name: e-norm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
     - 5432:5432
    networks:
      - database


networks:
  database:
  web: