version: "3.8"

services:
  backend:
   build: ./backend
   container_name: e-norm_backend
   environment:
    - MONGODB_CONNSTRING=mongodb://database:27017
    - PORT:3000
  # Problème avec bcrypt
  #  volumes:
  #   - ./backend:/app
    # - /backend/node_modules/
   ports:
    - 3000:3000
   networks:
    - frontend
    - backend
   restart: unless-stopped

  frontend:
   build: ./frontend
   container_name: e-norm_frontend
   volumes:
    - ./frontend:/app
   ports:
    - 8080:80
   networks:
    - frontend
   restart: unless-stopped

  database:
   image: mongo:latest
   container_name: e-norm_db
   ports:
    - 27017:27017
   networks:
    - backend
   restart: unless-stopped

networks:
  backend:
  frontend: