-- Up Migration
CREATE SCHEMA AUTHORIZATION admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA admin TO admin;
ALTER DEFAULT PRIVILEGES FOR ROLE admin IN SCHEMA admin
GRANT ALL PRIVILEGES ON TABLES TO admin;
-- Down Migration
DROP SCHEMA admin CASCADE;